### ISSUE TITLE
CI: fuzzing CI seems to not cache the corpus

### ISSUE THREAD

**Issue by Robbepop** [wasmi-labs/wasmi#1117]
It seems that even with the recent refactoring and improvements to the CI's caching behavior the fuzzing CI jobs still do not properly store and re-store their fuzzing corpuses and thus our fuzzing CI is practically useless.

Without the corpus in the cache the fuzzing CI has no memory of the past fuzzing artifacts and thus cannot built on-top of past successes and findings.

**Comment by Robbepop** [comment]
@gtrepta @Scott-Guest Just to be sure: has this been fixed in https://github.com/wasmi-labs/wasmi/pull/1234 ?

**Comment by gtrepta** [comment]
No, that PR didn't totally fix it. I think two issues here are that each job is sharing the same cache, and the corpus folder isn't considered when deciding to update the cache.

Given how much smaller the corpus is compared to the rust cache, I think it can be put into a separate caching step. Something like this:

```yaml
- name: Fuzz corpus caching
  uses: actions/cache@v4
  with:
    path: ${{ github.workspace }}/hfuzz_workspace
    key: fuzz-${{ matrix.fuzz_target }}-${{ github.run_id }}
    restore-keys: |
      fuzz-${{ matrix.fuzz_target }}
```
